from pathlib import Path


class RepositoryGenerator:
    def generate(self, name: str, output_root: str = "output/repository") -> Path:
        repository_path = Path(output_root) / name

        repository_path.mkdir(parents=True, exist_ok=True)

        (repository_path / "src").mkdir(exist_ok=True)
        (repository_path / "tests").mkdir(exist_ok=True)
        (repository_path / "docs").mkdir(exist_ok=True)

        readme_path = repository_path / "README.md"
        if not readme_path.exists():
            readme_path.write_text(
                f"# {name}\n\nGenerated by Kairos Builder Enterprise V1.\n",
                encoding="utf-8",
            )

        return repository_path
