from __future__ import annotations

from pathlib import Path
from typing import Any

from builder.context.project_context import ProjectContext
from builder.execution.execution_engine import ExecutionEngine
from builder.generator.registry import default_registry
from builder.plugins.market_data_engine import MarketDataEngine
from builder.plugins.money_flow_engine import MoneyFlowEngine
from builder.plugins.universe_provider import UniverseProvider
from builder.plugins.universe_scanner import UniverseScanner
from builder.sprint.sprint_manager import SprintManager
from builder.workflow.builder_workflow import BuilderWorkflow


class BuilderService:
    def __init__(self, context: ProjectContext | None = None) -> None:
        self.context = context or ProjectContext()

        self.market = MarketDataEngine()
        self.flow = MoneyFlowEngine()
        self.scanner = UniverseScanner()
        self.universe = UniverseProvider()
        self.executor = ExecutionEngine()

        self.workflow = BuilderWorkflow(context=self.context)
        self.sprint_manager = SprintManager()
        self.generator_registry = default_registry()

    def create_project(
        self,
        name: str,
        output_root: str | Path = "output/projects",
    ) -> Path:
        project_path = Path(output_root) / name
        project_path.mkdir(parents=True, exist_ok=True)

        for folder in (
            project_path / "src",
            project_path / "tests",
            project_path / "docs",
        ):
            folder.mkdir(parents=True, exist_ok=True)

        self._write_if_missing(
            project_path / "README.md",
            f"# {name}\n\nGenerated by Kairos Builder Enterprise.\n",
        )
        self._write_if_missing(
            project_path / "pyproject.toml",
            self._default_pyproject(name),
        )
        self._write_if_missing(
            project_path / ".gitignore",
            self._default_gitignore(),
        )

        return project_path

    def generate(
        self,
        generator_type: str,
        name: str,
        output_root: str | Path | None = None,
    ) -> Any:
        normalized = generator_type.strip().lower()
        generator = self.generator_registry.create(normalized)

        if output_root is None:
            output_root = self._default_generator_output(normalized)

        return generator.generate(
            name,
            str(output_root),
        )

    def workflow_verify(self) -> str:
        return "\n".join(self.workflow.verify_plan())

    def workflow_commit_message(
        self,
        scope: str,
        message: str,
        commit_type: str = "feat",
    ) -> str:
        return self.sprint_manager.build_commit_message(
            commit_type,
            scope,
            message,
        )

    def project_version(self) -> str:
        return self.context.version()

    def project_sprint(self) -> int:
        return self.context.current_sprint()

    def run_full_market_scan(self):
        universe = self.universe.get_all_us_stocks()
        ranked = self.scanner.scan_all(
            universe,
            self.market,
            self.flow,
        )
        return ranked[:20]

    def execute_top_scan(self, capital=10000):
        universe = self.universe.get_all_us_stocks()
        ranked = self.scanner.scan_all(
            universe,
            self.market,
            self.flow,
        )

        filtered = ranked[:10]
        total = sum(x["score"] for x in filtered) or 1

        adjusted = []

        for item in filtered:
            weight = item["score"] / total

            adjusted.append(
                {
                    "ticker": item["ticker"],
                    "score": item["score"],
                    "signal": item["signal"],
                    "allocation": capital * weight,
                }
            )

        return self.executor.execute_top(
            adjusted,
            capital,
        )

    def start_live(self, capital: int = 10000):
        return self.execute_top_scan(capital)

    def stop_trading(self) -> str:
        return "Trading stopped"

    @staticmethod
    def _default_generator_output(
        generator_type: str,
    ) -> Path:
        return Path("output") / generator_type

    @staticmethod
    def _write_if_missing(
        path: Path,
        content: str,
    ) -> None:
        if not path.exists():
            path.write_text(
                content,
                encoding="utf-8",
            )

    @staticmethod
    def _default_pyproject(name: str) -> str:
        package_name = (
            name.replace("-", "_")
            .replace(" ", "_")
            .lower()
        )

        return (
            "[project]\n"
            f'name = "{package_name}"\n'
            'version = "0.1.0"\n'
            'description = "Generated by Kairos Builder Enterprise."\n'
            'requires-python = ">=3.11"\n'
        )

    @staticmethod
    def _default_gitignore() -> str:
        return (
            "__pycache__/\n"
            "*.py[cod]\n"
            ".pytest_cache/\n"
            ".venv/\n"
            "dist/\n"
            "build/\n"
        )