from pathlib import Path

from builder.domain.generation_request import GenerationRequest
from builder.domain.generation_result import GenerationResult


class GeneratorService:
    def generate(self, request: GenerationRequest) -> GenerationResult:
        output_path = Path(request.output_path)

        if output_path.exists():
            return GenerationResult(
                target_type=request.target_type,
                name=request.name,
                output_path=str(output_path),
                created=False,
            )

        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(
            self._build_content(request),
            encoding="utf-8",
        )

        return GenerationResult(
            target_type=request.target_type,
            name=request.name,
            output_path=str(output_path),
            created=True,
        )

    def _build_content(self, request: GenerationRequest) -> str:
        return f"""# Generated {request.target_type}

## Name

{request.name}

## Status

Generated by Kairos Builder Enterprise.
"""
